### ISSUE TITLE
Contribute RegexTester to Eclipse.org

### ISSUE THREAD

**Issue by vogella** [sbrosinski/RegexTester#4]
We would like to include the regex tester into our custom Eclipse distribution (voclipse.com). Could you create a p2 update site.

**Comment by Pontesegger** [comment]
I love this tool, too, so I created a p2 site for it, see my post:
http://codeandme.blogspot.de/2016/08/regular-expression-tester.html

Stephan, hope that is ok for you.

**Comment by sbrosinski** [comment]
Yes, great! Thank you. It's not really maintained anymore, since most Java developers I interact with switched to IntelliJ :-/ Great it is still working for you.

**Comment by vogella** [comment]
@sbrosinski would you be OK if I try to bring this code to Eclipse.org? I think it would be useful to have such  a tool in Eclipse and would be willing to maintain it. This would require that we can change the licence to EPL.

**Comment by sbrosinski** [comment]
@vogella that would be awesome. We can change the license to EPL.

**Comment by vogella** [comment]
Thanks @sbrosinski I check with Wayne from the foundation for the move.

**Comment by vogella** [comment]
@Pontesegger would you also like to help with the move and the code maintenance. Would be nice to have a few interested people working on it.

**Comment by sbrosinski** [comment]
I just changed the license to EPL. I'm also able to help if something comes up. Although I wrote most of that code 12 years ago (I think initially for Eclipse 2.2) and later refactored it for Eclipse 3.x. By now I can barely remember it. ;-)

**Comment by Pontesegger** [comment]
sure I can help to maintain. I already would have some ideas for improvements :)
Nice how a small blog post triggers things

**Comment by vogella** [comment]
@Pontesegger great to hear.. 

@sbrosinski If you understand you statements correct, you are not interested in actively maintaining the project. Correct? Otherwise you should also become project or at least committer status, if the project gets accepted for the foundation.

**Comment by sbrosinski** [comment]
@vogella correct. I'm available to answer questions regarding the existing source base, but I will not commit new things.

**Comment by wimjongman** [comment]
Thanks @sbrosinski.  Eclipse has strict IP rules so we have to start a process. In order for you to officially hand over the code we need you to create an Eclipse account (if you don't already have one) [1]

Once you have an account you can add yourself to the tracking bug [2]


[1] https://dev.eclipse.org/site_login/
[2] https://bugs.eclipse.org/bugs/show_bug.cgi?id=500331

**Comment by vogella** [comment]
@wimjongman I think I can start the IP process without @sbrosinski having a user.

**Comment by wimjongman** [comment]
You can start it but at some point IP needs a record where @sbrosinski states that he has written the software himself and has the right to contribute it under the EPL. Also all major contributors must be tracked and state the same thing.

**Comment by sbrosinski** [comment]
I got an Eclipse.org account, signed the ECA and added myself to the issue.
Apart from one small pull request (https://github.com/sbrosinski/RegexTester/pull/2) there have been no other contributors and I wrote all code myself.

**Comment by vogella** [comment]
We have done the preparation for the code contribution in https://github.com/vogellacompany/RegexTester

**Comment by vogella** [comment]
IP for code contribution https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13682

P.S. just noted that you also located in Hamburg. Maybe see you in the next Eclipse Democamp? https://wiki.eclipse.org/Eclipse_DemoCamps_Oxygen_2017/Hamburg

**Comment by vogella** [comment]
@makkimesser are you OK to change the license to EPL? AFAICS you did this commit https://github.com/sbrosinski/RegexTester/commit/90c0a5aae60e18734a3e10fc67fe321503e3462c and therefore you need to agree to the license change.

**Comment by makkimesser** [comment]
Yes, I am OK with the change of the license to EPL.

**Comment by vogella** [comment]
Code is now available via the e4.ui project. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=500331
